services:
  app:
    image: ghcr.io/anime-gaming-cafe/agc-homepage:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "300"
